export HEROKU_ORGANIZATION=trimbox
export HELPBASE_NGROK_DOMAIN=popular-neatly-ostrich.ngrok-free.app
export TRIMBOX_NGROK_DOMAIN=popular-neatly-ostrich.ngrok-free.app
export TRIMBOX_NPM_TOKEN=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
